services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: spark_notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - JUPYTER_TOKEN=mourao
    volumes:
      - ./work:/home/jovyan/work
    working_dir: /home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=spark


  # docker compose up jupyter para abrir o Jupyter.
